services:
  - type: web
    name: ai-model-service
    env: python
    region: oregon
    plan: free
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      # Pre-download BioBERT model + tokenizer to reduce startup time:
      python - <<PY
      from transformers import AutoTokenizer, AutoModel
      AutoTokenizer.from_pretrained("dmis-lab/biobert-base-cased-v1.1")
      AutoModel.from_pretrained("dmis-lab/biobert-base-cased-v1.1")
      print("Downloaded BioBERT into cache.")
      PY
    startCommand: gunicorn ai_service:app --workers 2 --bind 0.0.0.0:$PORT --timeout 300
